#include "../config.h"
#include "../../include/global.h"
#include "../../include/constants/trainer_classes.h"
#include "../../include/constants/songs.h"
#include "../../include/constants/species.h"
/*
music_tables.c
	set up music for each trainer class

tables to edit:
	gClassBasedTrainerEncounterBGM
	gClassBasedBattleBGM
	gWildSpeciesBasedBattleBGM
	gRandomBattleMusicOptions

*/

//Finish Wild Songs for Unbound

#ifndef UNBOUND

//Modify These

#ifdef ENCOUNTER_MUSIC_BY_CLASS
const u16 gClassBasedTrainerEncounterBGM[NUM_TRAINER_CLASSES] =
{
	[CLASS_TEAM_MAGMA] = BGM_EYE_CREEPY,
	[CLASS_YOUNGSTER] = BGM_EYE_BOY,
	[CLASS_BUG_CATCHER] = BGM_EYE_BOY,
	[CLASS_LASS] =  BGM_EYE_GIRL,
	[CLASS_SAILOR] = BGM_EYE_BOY,
	[CLASS_CAMPER] = BGM_EYE_BOY,
	[CLASS_PICNICKER] =  BGM_EYE_GIRL,
	[CLASS_POKEMANIAC] = BGM_EYE_CREEPY,
	[CLASS_SUPER_NERD] = BGM_EYE_CREEPY,
	[CLASS_HIKER] = BGM_EYE_BOY,
	[CLASS_BIKER] = BGM_EYE_BOY,
	[CLASS_BURGLAR] = BGM_EYE_CREEPY,
	[CLASS_ENGINEER] = BGM_EYE_BOY,
	[CLASS_FISHERMAN] = BGM_EYE_BOY,
	[CLASS_SWIMMER_M] = BGM_EYE_BOY,
	[CLASS_CUE_BALL] = BGM_EYE_BOY,
	[CLASS_GAMBLER] = BGM_EYE_BOY,
	[CLASS_BEAUTY] =  BGM_EYE_GIRL,
	[CLASS_SWIMMER_F] =  BGM_EYE_GIRL,
	[CLASS_PSYCHIC] = BGM_EYE_BOY,
	[CLASS_ROCKER] = BGM_EYE_BOY,
	[CLASS_JUGGLER] = BGM_EYE_BOY,
	[CLASS_TAMER] = BGM_EYE_BOY,
	[CLASS_BIRD_KEEPER] = BGM_EYE_BOY,
	[CLASS_BLACK_BELT] = BGM_EYE_BOY,
	[CLASS_RIVAL] = BGM_EYE_BOY,
	[CLASS_SCIENTIST] = BGM_EYE_BOY,
	[CLASS_BOSS] = BGM_EYE_BOY,
	[CLASS_LEADER] = BGM_EYE_BOY,
	[CLASS_TEAM_ROCKET] = BGM_EYE_CREEPY,
	[CLASS_COOLTRAINER] = BGM_EYE_BOY,
	[CLASS_ELITE_4] = BGM_EYE_BOY,
	[CLASS_GENTLEMAN] = BGM_EYE_BOY,
	[CLASS_RIVAL_2] = BGM_EYE_BOY,
	[CLASS_CHAMPION] = BGM_EYE_BOY,
	[CLASS_CHANNELER] = BGM_EYE_CREEPY,
	[CLASS_TWINS] =  BGM_EYE_GIRL,
	[CLASS_COOL_COUPLE] = BGM_EYE_BOY,
	[CLASS_YOUNG_COUPLE] = BGM_EYE_BOY,
	[CLASS_CRUSH_KIN] = BGM_EYE_BOY,
	[CLASS_SIS_AND_BRO] =  BGM_EYE_GIRL,
	[CLASS_PKMN_PROF] = BGM_EYE_BOY,
	[CLASS_PLAYER] = BGM_EYE_BOY,
	[CLASS_CRUSH_GIRL] =  BGM_EYE_GIRL,
	[CLASS_TUBER] = BGM_EYE_BOY,
	[CLASS_PKMN_BREEDER] = BGM_EYE_BOY,
	[CLASS_PKMN_RANGER] = BGM_EYE_BOY,
	[CLASS_AROMA_LADY] =  BGM_EYE_GIRL,
	[CLASS_RUIN_MANIAC] = BGM_EYE_BOY,
	[CLASS_LADY] =  BGM_EYE_GIRL,
	[CLASS_PAINTER] =  BGM_EYE_GIRL,
};
#endif

const u16 gClassBasedBattleBGM[NUM_TRAINER_CLASSES] =
{
	[CLASS_CHAMPION] = BGM_BATTLE_CHAMPION,
	[CLASS_LEADER] = BGM_BATTLE_GYM_LEADER,
	[CLASS_ELITE_4] = BGM_BATTLE_E4,
	[CLASS_PKMN_TRAINER_1] = BGM_BATTLE_RSE_TRAINER,
	[CLASS_PKMN_TRAINER_2] = BGM_BATTLE_RSE_TRAINER,
	[CLASS_TEAM_AQUA] = BGM_BATTLE_CHAMPION,        //Final Giovanni
	[CLASS_AROMA_LADY_RS] = BGM_BATTLE_RSE_GYM_LEADER, //Johto Gym Leaders
	// [CLASS_AROMA_LADY_RS] = BGM_JOHTO_GYM_LEADER, //Johto Gym Leaders
	[CLASS_RUIN_MANIAC_RS] = BGM_BATTLE_RSE_TRAINER, //Dumbass Kid
	[CLASS_BOSS] = BGM_BATTLE_RSE_GYM_LEADER,
	[CLASS_TEAM_MAGMA] = BGM_BATTLE_RSE_TRAINER,
	[CLASS_MAGMA_LEADER] = BGM_BATTLE_RSE_GYM_LEADER,
	[CLASS_INTERVIEWER] = BGM_BATTLE_RSE_GYM_LEADER,
	// [CLASS_AQUA_LEADER] = BGM_BATTLE_DEOXYS, 
};

const u16 gWildSpeciesBasedBattleBGM[] =
{
	[SPECIES_ARTICUNO] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_ZAPDOS] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_MOLTRES] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_ARTICUNO_G] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_ZAPDOS_G] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_MOLTRES_G] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_MEWTWO] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_MEW] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_ENTEI] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_RAIKOU] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_SUICUNE] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_HO_OH] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_LUGIA] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_CELEBI] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_LATIOS] = BGM_BATTLE_RSE_GYM_LEADER,
	[SPECIES_LATIAS] = BGM_BATTLE_RSE_GYM_LEADER,
	[SPECIES_GROUDON] = BGM_BATTLE_RSE_GYM_LEADER,
	[SPECIES_KYOGRE] = BGM_BATTLE_RSE_GYM_LEADER,
	[SPECIES_RAYQUAZA] = BGM_BATTLE_RSE_GYM_LEADER,
	[SPECIES_JIRACHI] = BGM_BATTLE_RSE_GYM_LEADER,
	[SPECIES_DEOXYS] = BGM_BATTLE_DEOXYS,
	[SPECIES_VICTINI] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_COBALION] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_TERRAKION] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_VIRIZION] =  BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_TORNADUS] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_THUNDURUS] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_LANDORUS] = BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_KELDEO] =  BGM_BATTLE_LEGENDARY_BIRDS,
	[SPECIES_MELOETTA] = BGM_BATTLE_LEGENDARY_BIRDS,
};

const u16 gRandomBattleMusicOptions[] =
{
	BGM_BATTLE_WILD,
	BGM_BATTLE_TRAINER,
	BGM_BATTLE_GYM_LEADER,
	BGM_BATTLE_CHAMPION,
	BGM_BATTLE_LEGENDARY_BIRDS,
	BGM_BATTLE_E4,
	BGM_BATTLE_RSE_GYM_LEADER,
	BGM_BATTLE_DEOXYS,
};

#endif

const u8 gRandomBattleMusicOptionsLength = ARRAY_COUNT(gRandomBattleMusicOptions);
const u16 gWildSpeciesBasedBattleBGMLength = ARRAY_COUNT(gWildSpeciesBasedBattleBGM);
