
/*
@;format: attacking type, defending type, damage multiplier
@;the multiplier is a (decimal) fixed-point number:
@�2.0 TYPE_MUL_SUPER_EFFECTIVE
@�1.0 TYPE_MUL_NORMAL
@;�0.5 TYPE_MUL_NOT_EFFECTIVE
@;�0.0 TYPE_MUL_NO_EFFECT
*/

const u8 gTypeEffectiveness[NUMBER_OF_MON_TYPES][NUMBER_OF_MON_TYPES] =
{
	[TYPE_NORMAL]=
	{
		[TYPE_ICE] = TYPE_MUL_NOT_EFFECTIVE,	// Ice is hard like Rock and Steel
		[TYPE_ROCK] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_STEEL] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_GHOST] = TYPE_MUL_NO_EFFECT,
	},
	[TYPE_FIRE]=
	{
		[TYPE_FIRE] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_WATER] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_GRASS] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_ICE] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_BUG] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_ROCK] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_DRAGON] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_STEEL] = TYPE_MUL_SUPER_EFFECTIVE,
	},
	[TYPE_WATER]=
	{
		[TYPE_FIRE] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_WATER] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_GRASS] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_GROUND] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_ROCK] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_DRAGON] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_POISON] = TYPE_MUL_SUPER_EFFECTIVE,	// Dilution
		[TYPE_ICE] = TYPE_MUL_NOT_EFFECTIVE,		// Add a little water to ice, it simply freezes over
	},
	[TYPE_ELECTRIC]=
	{
		[TYPE_WATER] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_ELECTRIC] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_GRASS] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_GROUND] = TYPE_MUL_NO_EFFECT,
		[TYPE_FLYING] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_DRAGON] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_STEEL] = TYPE_MUL_SUPER_EFFECTIVE,	// Conduction (same thought as water)
	},
	[TYPE_GRASS]=
	{
		[TYPE_FIRE] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_WATER] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_GRASS] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_POISON] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_GROUND] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_FLYING] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_BUG] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_ROCK] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_DRAGON] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_STEEL] = TYPE_MUL_NOT_EFFECTIVE,
	},
	[TYPE_ICE]=
	{
		[TYPE_WATER] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_ELECTRIC] = TYPE_MUL_SUPER_EFFECTIVE, // Electronics, especially batteries, struggle in the cold
		[TYPE_GRASS] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_ICE] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_ROCK] = TYPE_MUL_SUPER_EFFECTIVE,		// Water freezes and splits rocks
		[TYPE_GROUND] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_FLYING] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_DRAGON] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_STEEL] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_FIRE] = TYPE_MUL_NOT_EFFECTIVE,
	},
	[TYPE_FIGHTING]=
	{
		[TYPE_NORMAL] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_ICE] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_POISON] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_FLYING] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_PSYCHIC] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_BUG] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_FAIRY] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_ROCK] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_DARK] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_STEEL] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_GHOST] = TYPE_MUL_NO_EFFECT,
	},
	[TYPE_POISON]=
	{
		[TYPE_WATER] = TYPE_MUL_SUPER_EFFECTIVE,	// Contamination
		[TYPE_GRASS] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_FAIRY] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_POISON] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_GROUND] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_ROCK] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_GHOST] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_STEEL] = TYPE_MUL_NOT_EFFECTIVE,		// Corrosion, but still resist. Maybe make neutral?
	},
	[TYPE_GROUND]=
	{
		[TYPE_FIRE] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_ELECTRIC] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_GRASS] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_POISON] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_FLYING] = TYPE_MUL_NO_EFFECT,
		[TYPE_BUG] = TYPE_MUL_NOT_EFFECTIVE,
		// [TYPE_ROCK] = TYPE_MUL_SUPER_EFFECTIVE, // Rebalance. Rock buff, Ground nerf
		[TYPE_STEEL] = TYPE_MUL_SUPER_EFFECTIVE,
	},
	[TYPE_FLYING]=
	{
		[TYPE_ELECTRIC] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_GRASS] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_FIGHTING] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_BUG] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_ROCK] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_STEEL] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_ICE] = TYPE_MUL_NOT_EFFECTIVE,		// Ice resists wind
	},
	[TYPE_PSYCHIC]=
	{
		[TYPE_FIGHTING] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_POISON] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_PSYCHIC] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_DARK] = TYPE_MUL_NOT_EFFECTIVE,		// Remove immunity. I just don't like it...
		[TYPE_STEEL] = TYPE_MUL_SUPER_EFFECTIVE,	// ala spoon bending
	},
	[TYPE_BUG]=
	{
		[TYPE_FIRE] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_GRASS] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_FIGHTING] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_POISON] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_FLYING] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_PSYCHIC] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_GHOST] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_DARK] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_STEEL] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_FAIRY] = TYPE_MUL_SUPER_EFFECTIVE,	// Rebalance. Bug buff, Fairy nerf
	},
	[TYPE_ROCK]=
	{
		[TYPE_FIRE] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_ICE] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_FIGHTING] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_GROUND] = TYPE_MUL_NOT_EFFECTIVE,	
		[TYPE_FLYING] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_BUG] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_STEEL] = TYPE_MUL_NOT_EFFECTIVE,
	},
	[TYPE_GHOST]=
	{
		[TYPE_NORMAL] = TYPE_MUL_NO_EFFECT,
		[TYPE_PSYCHIC] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_DARK] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_GHOST] = TYPE_MUL_SUPER_EFFECTIVE,
	},
	[TYPE_DRAGON]=
	{
		[TYPE_DRAGON] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_STEEL] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_FAIRY] = TYPE_MUL_NOT_EFFECTIVE,		// Remove immunity. I just don't like it...
	},
	[TYPE_DARK]=
	{
		[TYPE_FIGHTING] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_PSYCHIC] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_GHOST] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_DARK] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_FAIRY] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_STEEL] = TYPE_MUL_NOT_EFFECTIVE		// Restoring change from previous gens. "Dirty" fighting lacks discipline to harm steel
	},
	[TYPE_STEEL]=
	{
		[TYPE_STEEL] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_FIRE] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_WATER] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_ELECTRIC] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_ICE] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_ROCK] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_FAIRY] = TYPE_MUL_SUPER_EFFECTIVE,
	},
	[TYPE_FAIRY]=
	{
		[TYPE_GRASS] = TYPE_MUL_NOT_EFFECTIVE,		// Faewood + rebalance. Grass buff, Fairy nerf
		[TYPE_BUG] = TYPE_MUL_NOT_EFFECTIVE,		// Rebalance. Bug buff, Fairy nerf
		[TYPE_POISON] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_STEEL] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_FIRE] = TYPE_MUL_NOT_EFFECTIVE,
		[TYPE_FIGHTING] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_DRAGON] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_DARK] = TYPE_MUL_SUPER_EFFECTIVE,
		[TYPE_PSYCHIC] = TYPE_MUL_NOT_EFFECTIVE,	// Rebalance. Psychic buff, Fairy nerf. Dark sort of opposite of Fairy (Light). Psychic weak to Dark, so resists Light 
	},
};